window:

font:
  normal:
    family: iosevka
    style: iosevka-medium
  bold:
    family: iosevka
    style: iosevka-bold
  italic:
    family: iosevka
    style: iosevka-italic
  bold_italic:
    family: iosevka
    style: iosevka-bolditalic

draw_bold_text_with_bright_colors: true

size: 15

window:
   opacity: 0.92
   padding:
    x: 7
    y: 5

use_thin_strokes: true
custom_cursor_colors: true


# gruvbox Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0x1d2021'
    foreground: '0xd4be98'

  cursor:
    text: '0xffffff'
    cursor: '0x4d4d4c'

  # Normal colors
  normal:
    black:   '0x1D2021'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xd8a657'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    aqua:    '0x89b482'
    white:   '0xd4be98'

  # Bright colors
  bright:
    black:   '0x928374'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xd8a657'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    aqua:    '0x89b482'
    white:   '0xd4be98'

  indexed_colors:
    - { index: 16, color: '0xe78a4e' }
    - { index: 17, color: '0xc14a4a' }

shell:
  program: /usr/bin/zsh

bell:
  animation: EaseOutExpo
  color: '0xffffff'
  duration: 0

mouse:
  hide_when_typing: true
  unfocused_hollow: true

key_bindings:
  - { key: V,        mods: alt,       action: Paste                        }
  - { key: C,        mods: alt,       action: Copy                         }
  - { key: Equals,   mods: Command,       action: IncreaseFontSize             }
  - { key: Minus,    mods: Command,       action: DecreaseFontSize             }
  - { key: Minus,    mods: Command|Shift, action: ResetFontSize                }
